### ISSUE TITLE
GlumSak 2.3.2.2 recognized as malicious when downloading

### ISSUE THREAD

**Issue by RedPana** [Glumboi/GlumSak#22]
2.3.2.2 is recognized as malicious when downloading in Firefox and Chromium-based browsers. When downloading previous versions (eg; 2.3.2.1) the file does not get flagged.

Chrome:
![image](https://github.com/Glumboi/GlumSak/assets/91498329/a1c6ce43-2381-448c-ba0b-61a55585f9bf)

Firefox:
![image](https://github.com/Glumboi/GlumSak/assets/91498329/c681bc72-b5da-4410-b923-780924806546)

**Comment by Glumboi** [comment]
This is known to me and definitely not intentional, this Project currently is on ice due to the high amount of Projects I have in the mean time. If you are concerned I would suggest either using the portable Version or not use the Program at all. These flags are probably due to the updates I did to the installer. Will look into it as soon as I have more time.

**Comment by LeVraiRoiDHyrule** [comment]
Hi, same here, the virustotal score isn't so good : https://www.virustotal.com/gui/file/1c2321a71f865a3dd53737beab0857f427930530f7707ee6c87b0760e3e8d869

**Comment by Glumboi** [comment]
I now made changes to the Installer which reduces the flags to 4, it's already updated. Version Number did not increase.
